### ISSUE TITLE
[macOS]  Sonoma 14.4, keyboard and mouse unresonsive

### ISSUE THREAD

**Issue by johanhenselmans** [Coopydood/ultimate-macOS-KVM#78] opened 2024-03-08 09:00 UTC
### Describe the Issue

I updated to 14.4,  upgrade went OK, but now my keyboard and mouse are unresponsive. 

### Reproduce the Issue

I did an upgrade inside the qemu MacOS. 
I noticed that error messages I had before, about usb that popped up in the terminal were gone when I started via boot.sh. 
Also, I can not get into the BIOS anymore via EFI Shell. I used to be able to get back to the BIOS (to set the screen size for instance)
Any way I can get ULTMOS working again? 

### Expectation

A running 14.4 with a working keyboard and mouse.

### Operating System

Ubuntu 23.10

### Kernel

6.5.0-25

### Processor

11th Gen Intel® Core™ i7-1165G7 × 8

### RAM (in GB)

32

### GPU(s)

???

### Version

ULTMOS v0.11.1

### Branch

main

### Generated Script File

```shell
#!/usr/bin/env bash
# shellcheck disable=SC2054

#
#   APC-RUN_11-02-2024_10-30-32
#
#   THIS FILE WAS GENERATED USING AUTOPILOT.
#
#   To boot this script, run the following command:
#   $ ./boot.sh
#

#
#	boot.sh
#	Created by Coopydood as part of the ultimate-macOS-KVM project.
#
#	Profile: https://github.com/Coopydood
#	Repo: https://github.com/Coopydood/ultimate-macOS-KVM
#
#	Adapted from OSX-KVM among others.
#	Greetz to TheNickDude, Dortania, khoalia, foxlet, and other contributors :]
#


ID="macOS"
NAME="macOS 14"
FILE="boot.sh"

ULTMOS=0.11.0
IGNORE_FILE=0
REQUIRES_SUDO=0
VFIO_PTA=0
VFIO_DEVICES=0
GEN_EPOCH=1707643832
FEATURE_LEVEL=7
VERBOSE=1
DISCORD_RPC=0

SCREEN_RES="1920x1080"
ALLOCATED_RAM="8G"
CPU_SOCKETS="1"
CPU_CORES="2"
CPU_THREADS="4"
CPU_MODEL="Haswell-noTSX"
CPU_FEATURE_ARGS="+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

REPO_PATH="/home/localadmin/Documents/ultimate-macOS-KVM"
OVMF_DIR="/home/localadmin/Documents/ultimate-macOS-KVM/ovmf"

VFIO_ID_0="$USR_VFIO_ID_0"
VFIO_ID_1="$USR_VFIO_ID_1"
VFIO_ROM="$USR_VFIO_ROM"

USB_DEVICES="$USR_USB_DEVICES"

NETWORK_DEVICE="vmxnet3"
MAC_ADDRESS="00:16:cb:00:21:09"

OS_ID="Sonoma"

HDD_PATH="$REPO_PATH/HDD.qcow2"
DISK_TYPE="HDD"

#   You should not have to touch anything below this line, especially if you
#   don't really know what you're doing. It'll probably break something.

args=(
-global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off
-enable-kvm -m "$ALLOCATED_RAM" -cpu "$CPU_MODEL",kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,"$CPU_FEATURE_ARGS"
-machine q35
-usb -device usb-kbd -device usb-tablet 
#USB_DEV_BEGIN
#USB_DEV_END
-smp "$CPU_THREADS",cores="$CPU_CORES",sockets="$CPU_SOCKETS"
-device usb-ehci,id=ehci
-device qemu-xhci,id=xhci
-device pcie-root-port,bus=pcie.0,slot=1,x-speed=16,x-width=32
#VFIO_DEV_BEGIN
#VFIO_DEV_END
-device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
-drive if=pflash,format=raw,readonly=on,file="$OVMF_DIR/OVMF_CODE.fd"
-drive if=pflash,format=raw,file="$OVMF_DIR/OVMF_VARS.fd"
-smbios type=2
-device ich9-intel-hda -device hda-duplex
-device ich9-ahci,id=sata
-drive id=OpenCore,if=none,format=qcow2,file="$REPO_PATH/boot/OpenCore.qcow2"
-drive id=HDD,if=none,file="$HDD_PATH",format=qcow2
-device ide-hd,bus=sata.2,drive=OpenCore
-device ide-hd,bus=sata.3,drive=HDD,rotation_rate=7200

############## REMOVE THESE LINES AFTER MACOS INSTALLATION ###############
#-drive id=BaseSystem,if=none,file="$REPO_PATH/BaseSystem.img",format=raw
#-device ide-hd,bus=sata.4,drive=BaseSystem
##########################################################################
-usb -device usb-host,productid=0x4213,vendorid=0x2237
-netdev user,id=net0 -device "$NETWORK_DEVICE",netdev=net0,id=net0,mac="$MAC_ADDRESS"
-device qxl-vga,vgamem_mb=128,vram_size_mb=128    
-monitor stdio
#-display none
#-vga qxl

################ UNCOMMENT IF YOU WANT TO USE VNC MONITOR ################
#-vnc 0.0.0.0:1,password=on -k en-us
##########################################################################

)

while getopts d: flag
do
    case "${flag}" in
        d) DISCORD_RPC=${OPTARG};;
    esac
done

if [ $VERBOSE = 1 ]
then
echo
echo \ \ \──────────────────────────────────────────────
echo \ \ \ \ \ $NAME
echo \ \ \ \ \ macOS $OS_ID
echo
echo \ \ \ \ \ $FILE
echo \ \ \ \ \ Built with ULTMOS v$ULTMOS
echo \ \ \ \ \ Using $CPU_MODEL CPU model
if [ $REQUIRES_SUDO = 1 ]
then
echo \ \ \ \ \ Superuser privileges enabled
fi
if [ $VFIO_PTA = 1 ]
then
echo \ \ \ \ \ Passthrough enabled
else
echo \ \ \ \ \ Passthrough disabled
fi
if [ $DISCORD_RPC = 1 ]
then
echo \ \ \ \ \ Discord RPC enabled
else
echo \ \ \ \ \ Discord RPC disabled
fi
echo \ \ \──────────────────────────────────────────────
echo
fi

if [ $DISCORD_RPC = 1 ]
then
"$REPO_PATH/scripts/drpc.py" --os "$OS_ID" --pt $VFIO_DEVICES --wd "$REPO_PATH" &
fi

qemu-system-x86_64 "${args[@]}"

if [ $DISCORD_RPC = 1 ]
then
pkill -f drpc.py
fi
```

### Generated Log File

```bash
ULTMOS AUTOPILOT LOG 11-02-2024 05:33:12
──────────────────────────────────────────────────────────────
[05:33:12.802][ ✦ ]:  ULTMOS v0.11.0
[05:33:12.802][ ✦ ]:   
[05:33:12.802][ ✦ ]:  Name       : AutoPilot
[05:33:12.802][ ✦ ]:  File       : autopilot.py
[05:33:12.802][ ✦ ]:  Identifier : APC
[05:33:12.802][ ✦ ]:  Vendor     : Coopydood
[05:33:12.802][ ✦ ]:   
[05:33:12.802][ ✦ ]:  Logging to ./logs/APC_RUN_11-02-2024_05-33-12.log
[05:33:12.802][ ⚠ ]:  Unable to initialise Discord rich presence module, disabling for this session
[05:33:12.802][ ✦ ]:  Displaying menu
[05:33:12.802][ ✔ ]:  Menu displayed
[05:33:12.802][ ➜ ]:  Waiting on user input
[05:33:16.903][ ✔ ]:  User input received
[05:33:16.904][ ✔ ]:  ───────────────── STARTING INTERROGATION SEQUENCE ─────────────────
[05:33:16.904][ ✦ ]:  FEATURE LEVEL 7
[05:33:16.904][ ✔ ]:  Stage 1 sequence initiated
[05:33:16.904][ ✔ ]:  Removing stale blobs
[05:33:21.618][ ✔ ]:  Using default value of boot.sh
[05:33:21.619][ ✔ ]:  Stage 2 sequence initiated
[05:33:23.582][ ✔ ]:  Stage 2 sequence initiated
[05:33:23.582][ ✦ ]:  Custom value requested, setting up
[05:33:27.210][ ✔ ]:  Custom value was set to 12
[05:33:27.211][ ✔ ]:  Stage 3 sequence initiated
[05:33:36.951][ ✔ ]:  Stage 3 sequence initiated
[05:33:36.951][ ✦ ]:  Custom value requested, setting up
[05:33:39.480][ ✔ ]:  Custom value was set to 4
[05:33:39.481][ ✔ ]:  Stage 4 sequence initiated
[05:33:42.538][ ✔ ]:  Using default value of 2
[05:33:42.538][ ✔ ]:  Stage 5 sequence initiated
[05:33:53.896][ ✔ ]:  Using default value of Haswell-noTSX
[05:33:53.896][ ✔ ]:  Stage 6 sequence initiated
[05:33:55.839][ ✔ ]:  Using default value of +ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check
[05:33:55.839][ ✔ ]:  Stage 7 sequence initiated
[05:33:58.486][ ✔ ]:  Stage 7 sequence initiated
[05:33:58.487][ ✦ ]:  Custom value requested, setting up
[05:33:58.487][ ➜ ]:  Waiting for user input
[05:34:03.125][ ✔ ]:  User input received
[05:34:03.125][ ✔ ]:  Custom value was set to 8G
[05:34:03.125][ ✔ ]:  Stage 8 sequence initiated
[05:34:08.704][ ✔ ]:  Using default value of 80G
[05:34:08.704][ ✔ ]:  Stage 9 sequence initiated
[05:34:33.907][ ✔ ]:  Will set disk up as NVMe
[05:34:33.907][ ✔ ]:  Stage 10 sequence initiated
[05:34:41.240][ ✔ ]:  Using default value of vmxnet3
[05:34:41.241][ ✔ ]:  Stage 11 sequence initiated
[05:34:43.664][ ✔ ]:  Using default value of 00:16:cb:00:21:09
[05:34:43.665][ ✔ ]:  Stage 12 sequence initiated
[05:34:48.703][ ✦ ]:  Arming download mechanism
[05:34:48.703][ ✔ ]:  Downloader armed, will be triggered by AP flow
[05:34:48.703][ ✔ ]:  Stage 13 sequence initiated
[05:34:51.221][ ✔ ]:  Stage 13 sequence initiated
[05:34:51.221][ ✦ ]:  Custom value requested, setting up
[05:35:03.600][ ✔ ]:  Custom value was set to 1920x1080
[05:35:03.600][ ✔ ]:  Stage 14 sequence initiated
[05:35:09.475][ ✔ ]:  Using default value of True
[05:35:09.475][ ✔ ]:  Interrogation complete, displaying summary and AP autoflow sliproad
[05:35:12.396][ ✦ ]:  Handoff started, user preferences saved
[05:35:12.396][ ✔ ]:  ───────────────── STARTING AUTOPILOT AUTOFLOW ─────────────────
[05:35:12.396][ ✦ ]:  Here we go!
[05:35:14.396][ ✔ ]:  Updating status UI
[05:35:17.397][ ✦ ]:  STARTING PREPARE PHASE
[05:35:17.397][ ✔ ]:  Updating status UI
[05:35:17.397][ ✦ ]:  Setting up environment
[05:35:17.414][ ✔ ]:  Copied baseConfig into live working file
[05:35:18.415][ ✦ ]:  Setting up OpenCore image
[05:35:18.415][ ⚠ ]:  Existing OpenCore image found
[05:35:18.415][ ✦ ]:  Backing up existing image to ./boot/11-02-2024_05-35-18
[05:35:18.431][ ✔ ]:  Existing image backed up to ./boot/11-02-2024_05-35-18
[05:35:20.431][ ✦ ]:  Selecting appropriate OpenCore image
[05:35:20.431][ ✔ ]:  Selected NEW OpenCore image
[05:35:20.431][ ✦ ]:  Copying OpenCore image in place
[05:35:20.445][ ✔ ]:  OpenCore image copied
[05:35:20.445][ ✦ ]:  Copying OVMF code into place
[05:35:20.453][ ✦ ]:  Copying OVMF vars for resolution 1920x1080
[05:35:20.457][ ✔ ]:  OVMF files copied
[05:35:20.457][ ✦ ]:  Creating local OVMF variable store
[05:35:20.460][ ✦ ]:  Performing integrity check
[05:35:20.460][ ✔ ]:  Integrity check PASSED
[05:35:20.460][ ✔ ]:  Updated stage status, handing off to next stage
[05:35:20.461][ ✔ ]:  Updating status UI
[05:35:20.461][ ✦ ]:  STARTING INTEGRITY PHASE
[05:35:20.461][ ✔ ]:  Updating status UI
[05:35:24.461][ ✔ ]:  Integrity check PASSED
[05:35:24.461][ ✔ ]:  Updated stage status, handing off to next stage
[05:35:24.461][ ✔ ]:  Updating status UI
[05:35:24.462][ ✦ ]:  STARTING GENERATION PHASE
[05:35:24.462][ ✦ ]:  Working directory was captured as /home/localadmin/Documents/ultimate-macOS-KVM
[05:35:24.462][ ✔ ]:  Updating status UI
[05:35:24.462][ ✦ ]:  Scanning for file conflict
[05:35:28.462][ ⚠ ]:  Existing file with name boot.sh detected, asking the user
[05:35:33.102][ ⚠ ]:  Overwriting boot.sh
[05:35:33.103][ ✔ ]:  Updating status UI
[05:35:33.103][ ✦ ]:  Beginning variable injection
[05:35:33.112][ ✦ ]:  Checking disk type
[05:35:33.112][ ⚠ ]:  Disk type is NVMe, modifying device
[05:35:33.112][ ✔ ]:  Disk device updated
[05:35:33.112][ ✔ ]:  Variable injection complete
[05:35:33.112][ ✦ ]:  Stamping with ULTMOS version
[05:35:33.112][ ✔ ]:  Marked working script as using ULTMOS v0.11.0
[05:35:33.112][ ✦ ]:  Stamping with feature level
[05:35:33.112][ ✔ ]:  Marked working script as feature level 7
[05:35:33.112][ ✦ ]:  Checking if Discord rich presence is available
[05:35:33.989][ ⚠ ]:  Discord rich presence appears unavailable, will NOT enable in script
[05:35:33.989][ ✦ ]:  Adding OS ID marker
[05:35:33.989][ ✦ ]:  Setting up BaseSystem image attachment
[05:35:33.989][ ✦ ]:  Writing changes
[05:35:33.990][ ✔ ]:  Changes written to file
[05:35:33.990][ ✦ ]:  Performing integrity check
[05:35:33.990][ ✔ ]:  Integrity check PASSED
[05:35:33.990][ ✔ ]:  Updated stage status, handing off to next stage
[05:35:33.990][ ✔ ]:  Updating status UI
[05:35:34.990][ ✦ ]:  Checking XML creation preferences
[05:35:34.991][ ✔ ]:  XML creation requested, WILL be generating XML
[05:35:34.991][ ✔ ]:  Updating status UI
[05:35:34.991][ ✦ ]:  Pointing XML conversion tool to live script
[05:35:34.991][ ✦ ]:  Preparing live working XML
[05:35:34.995][ ✔ ]:  Base XML ready for live working
[05:35:34.995][ ✦ ]:  Parsing XML
[05:35:34.995][ ⚠ ]:  XML conversion tool APC integration doesn't support blob caching yet
[05:35:35.004][ ✦ ]:  Converting to XML format
[05:35:35.005][ ⚠ ]:  Virtual disk type is NVMe, modifying device
[05:35:35.005][ ✔ ]:  Disk device updated
[05:35:35.005][ ⚠ ]:  Disabling hard drive in XML
[05:35:35.005][ ✔ ]:  Converted to XML structure
[05:35:35.005][ ✦ ]:  Writing changes
[05:35:35.005][ ✔ ]:  Changes written to file
[05:35:37.005][ ✔ ]:  Updated stage status, handing off to next stage
[05:35:37.006][ ✔ ]:  Updating status UI
[05:35:40.006][ ✔ ]:  User requested a new macOS recovery image, arming downloader
[05:35:40.006][ ✦ ]:  STARTING REMOTE RECOVERY PHASE
[05:35:40.006][ ✔ ]:  Updating status UI
[05:35:42.007][ ✦ ]:  Setting target OS to 12
[05:35:42.007][ ✔ ]:  OS ID is valid, sending to dlosx script
[05:38:42.054][ ✦ ]:  Checking BaseSystem with a size of 3220185088
[05:38:42.054][ ✔ ]:  Integrity check PASSED
[05:38:42.054][ ✔ ]:  Updated stage status, handing off to next stage
[05:38:42.054][ ✔ ]:  Updating status UI
[05:38:45.055][ ✔ ]:  User requested a new HDD file, generation will go ahead
[05:38:45.055][ ✦ ]:  STARTING HARDDISK PHASE
[05:38:45.055][ ✔ ]:  Updating status UI
[05:38:47.056][ ✦ ]:  Scanning for file conflict
[05:38:47.056][ ⚠ ]:  Existing file with name HDD.qcow2 detected, asking the user
[05:38:47.056][ ➜ ]:  Waiting for user input
[05:44:23.803][ ✔ ]:  User input received
[05:44:23.803][ ⚠ ]:  Deleting HDD.qcow2
[05:44:23.837][ ✦ ]:  STARTING HARDDISK PHASE
[05:44:23.838][ ✔ ]:  Updating status UI
[05:44:25.838][ ✦ ]:  Scanning for file conflict
[05:44:25.838][ ✦ ]:  Generating hard disk image file
[05:44:28.876][ ✔ ]:  Hard disk image file generation verified
[05:44:28.876][ ✔ ]:  Updated stage status, handing off to next stage
[05:44:28.876][ ✔ ]:  Updating status UI
[05:44:30.877][ ✔ ]:  Hard disk image file generation verified
[05:44:30.877][ ✔ ]:  Updated stage status, handing off to next stage
[05:44:30.877][ ✔ ]:  Updating status UI
[05:44:32.877][ ✦ ]:  STARTING APPLY PHASE
[05:44:32.878][ ✔ ]:  Updating status UI
[05:44:34.878][ ✔ ]:  Integrity check PASSED
[05:44:34.878][ ✦ ]:  Dumping contents of baseConfig to memory
[05:44:34.878][ ✦ ]:  Stripping warning headers
[05:44:34.878][ ✦ ]:  Generating epoch timestamp
[05:44:34.878][ ✔ ]:  Epoch timestamped as 1707626674
[05:44:34.879][ ✦ ]:  Writing to file
[05:44:34.879][ ✔ ]:  Header verification complete
[05:44:34.879][ ✦ ]:  Moving working file into place
[05:44:34.885][ ✔ ]:  Moved working file into boot.sh successfully
[05:44:34.885][ ✔ ]:  Updated stage status, handing off to next stage
[05:44:34.885][ ✔ ]:  Updating status UI
[05:44:36.886][ ✦ ]:  STARTING PERMISSIONS PHASE
[05:44:36.886][ ✔ ]:  Updating status UI
[05:44:38.887][ ✦ ]:  Setting execute permissions
[05:44:38.890][ ✦ ]:  Setting readwrite permissions
[05:44:38.893][ ✔ ]:  Permissons set for new user files
[05:44:38.893][ ✔ ]:  Updated stage status, handing off to next stage
[05:44:38.893][ ✔ ]:  Updating status UI
[05:44:40.893][ ✔ ]:  Updating status UI
[05:44:40.894][ ✦ ]:  STARTING CLEANUP PHASE
[05:44:41.894][ ✦ ]:  Copying current session blobs into user backdir
[05:44:41.900][ ✦ ]:  Marking blobs as stale
[05:44:41.900][ ✦ ]:  Moving blobs into stale folder
[05:44:41.905][ ✔ ]:  Blob cleanup complete
[05:44:41.905][ ✔ ]:  Updated stage status, handing off to next stage
[05:44:41.905][ ✔ ]:  Updating status UI
[05:44:42.906][ ✦ ]:  Stopping timer
[05:44:44.906][ ✦ ]:  Updating variable definition
[05:44:44.907][ ✔ ]:  Timer was stopped with a recorded time of 571 seconds in live mode
[05:44:44.907][ ✔ ]:  AutoPilot stages complete, displaying user summary screen
[05:44:44.907][ ✔ ]:  ───────────────── AUTOPILOT COMPLETE! SESSION TIME WAS 571 SEC ─────────────────
[05:44:44.907][ ✦ ]:  XML generation was part of AP flow, offering import experience
[05:44:44.907][ ➜ ]:  Waiting for user input
[06:09:40.916][ ✔ ]:  User input received
[06:09:40.917][ ✦ ]:  Handing off to QEMU; booting boot.sh
[06:09:40.917][ ☠ ]:  bye
[06:09:40.917][ ☠ ]:  ───────────────── END OF LOGFILE ─────────────────
```

**Comment by Coopydood** [comment] 2024-03-08 19:24
Hi there, 

Can you try a soft reset of the repo?

You can do this from the Extras menu. (``Extras > Restore Tools``)

Many thanks

**Comment by johanhenselmans** [comment] 2024-03-09 09:15
I just tried. On every item I tried I got the same message:
=====================
   Integrity
   DAMAGED

   The repo integrity could not be verified.
   One or more files required to restore are damaged or missing.

   The script cannot continue.

===================
Also on Download and restore repository, 
Only Reset NVRAM did run.

**Comment by johanhenselmans** [comment] 2024-03-10 16:37
I have just reinstalled the whole installation in a new folder, and redownloaded 14.4. Same problem. It seems the opencore problems with keyboard and mouse and Metal have bitten us.

**Comment by Coopydood** [comment] 2024-03-10 21:46
Okay that's really strange.

I'll try repro it tonight. Perhaps try commenting out  the ``-device usb-ehci,id=ehci`` line in your boot script, and if that doesn't work, try commenting out the other ``-device qemu-xhci,id=xhci`` line, see if that makes a difference.

As for the reset tools- does the repo integrity check still fail on a new clone? Don't worry, we'll get it sorted.

Thanks again

**Comment by Keyluce** [comment] 2024-03-11 15:14
Same issue for me. I commented out both `-device usb-echi,id=ehci` and `device qemu-xhci,id=xhci` but didn't have any luck with it.

**Comment by Coopydood** [comment] 2024-03-11 16:13
In either of your cases- is this specific to 14.**4**?

**Comment by Keyluce** [comment] 2024-03-11 16:15
> In either of your cases- is this specific to 14.**4**?

Yep

**Comment by Coopydood** [comment] 2024-03-13 00:01
Okay. I'm going to attempt to reproduce it now

**Comment by Coopydood** [comment] 2024-03-13 00:29
Yep, hit it as soon as I booted the basesystem. 

I'll investigate it further, if any of you find any clues please let me know! Have a feeling this will be my new sleep-depriver!

**Comment by johanhenselmans** [comment] 2024-03-13 06:53
I'd have a look at the OpenCore repo, there is talk about problems with 14.4 over there too. See https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/1.4.2

**Comment by johanhenselmans** [comment] 2024-03-13 06:55
And https://github.com/dortania/OpenCore-Legacy-Patcher/issues/1125

**Comment by gpinter** [comment] 2024-03-14 00:27
I didn't see these posts and also updated to Sonoma 14.4.  Now my MacBook Pro 13" mid-2014 won't finish booting.  Get about half way, the keyboard lights up and then just hangs.  It will boot if I remove the Root Patches, but of course without WiFi and proper screen size support.  Hope this feedback help you all!

**Comment by eversiege** [comment] 2024-03-14 14:04
Thank you all for the issue. While we wait for a fix from Coopydood (and Dortania for that matter), I will see for a potential way for every one of you to downgrade to 14.3 in the meantime. 

For everyone that just joining in on this issue, **please do not update to 14.4 at this time.**

**Comment by bheardmedia** [comment] 2024-03-14 16:10
> I didn't see these posts and also updated to Sonoma 14.4. Now my MacBook Pro 13" mid-2014 won't finish booting. Get about half way, the keyboard lights up and then just hangs. It will boot if I remove the Root Patches, but of course without WiFi and proper screen size support. Hope this feedback help you all!

Are you updated to the latest OCLP? That should be fixed on most devices 2012 and newer. It is for my 2014 Macbook Air.

**Comment by Murasgul** [comment] 2024-03-16 12:29
Hi, Im sorry but can I conclude from this that it is safe for me to install 14.4 if I have metal, or should I wait nevertheless?

**Comment by gpinter** [comment] 2024-03-16 18:35
Sorry for the delay! I finally got back to troubleshooting and indeed you, bheardmedia, were right.  I was using an out of date OCLP. (I’m surprised it doesn’t auto check to see if there are newer versions available, but I guess I would have to run it to have it make that check, duhhh).  I downloaded the latest version, got it over to the Mac, re-ran the Root Patch upgrade and (after a couple of reboots) things seem to now be working fine.  My apologies for the not checking that first.  Note to self: always check to see if you have the latest version of OCLP before upgrading your system software!  Thanks all!!!

**Comment by luisoctavio77** [comment] 2024-03-17 03:06
What to do if (like me) the keyboard is unresponsive and you upgraded without reading?

I found out you can copy and paste commands to the terminal using SpotLight.

As one can only use the mouse to control most things, you want to do the following:

Open the Launchpad, open both Terminal and TextEdit (you may need to try clicking twice so a new terminal/document window actually opens).

Using the mouse, select all the text in the Terminal window now press right click (to show the contextual menu) and copy all the contents from the terminal window; then Paste into the TextEdit document. This is important as the Carriage Return can't even be entered in either Terminal or TextEdit (as the keyboard is unresponsive).

Next press Command + Space, to invoke the Spotlight window, there you can actually type anything and using the Mouse you can select what you typed and using the contextual menu copy/paste wherever you need in this case, the Terminal window.

You need to copy the whole line in the TextEdit window so that both the command and a carriage return get carried over in the clipboard, for this you may replace only the text in any particular line with the command but make sure there are additional lines down so you can actually copy the carriage return.

Some commands need sudo, you can copy and paste your password using this method. 

I know, it's annoying, but it worked for me: in this way I was able to delete the Local TimeMachine target, set a new one and create a backup. I will be reverting back to Ventura for the time being.

**Comment by joesfoo** [comment] 2024-03-18 06:56
If you have another computer, the keyboard also works via ssh, but, unfortunately, not via remote desktop.

**Comment by maryano** [comment] 2024-03-21 02:29
I had the "same" problems:
Problem1: - mouse & keyboard stuck, Solution; use an external USB kewboard.
Problem2: -mouse & keyboard (seems to be) stuck. Solution: In my case it was not kw problems. Whole system was really slow. I rebooted and it went ok. 

Problem 3: After I install root patches, when reboot to take effect, i get black screen and bar stucks at half. Nothing to do so I had to reinstall all OS again several times until i saw a solution. 
Solution: Before install root patches, go to OpenCore Patcher ->Settings ->Security,  and be sure to have checked:

ALLOW_UNRESTRICTED_FS (checked by default)
ALLOW_UNAUTHENTICATED_ROOT (checked by default)
ALLOW_UNTRUSTED_KEXTS (you need to check this one)

This worked for me!

**Comment by geneveu2** [comment] 2024-03-21 22:22
Hello, I have the same problem with the bluetooth that I can't connect the keyboard and mouse. But by USB external I can use another mouse and keyboard.

I have a mac mini 6.1 with sonoma 14.4 and opencore 1.4.2

The bluetooth didn't switch on it gets off inmediately. And by advanced settings its switch on but didn't detect any bluetooth devices.

**Comment by leithhobson** [comment] 2024-03-24 13:02
Thank you @luisoctavio77 
I too was an idiot who updated without checking first. Using your advice, I have been able to enable autologin, which seems to have resolved the unavailable keyboard issue, and now have been slowly bumbling my way around. - Still facing issues, however, hoping that I can hold out until OCLP is updated by our heros!

**Comment by pmrrm** [comment] 2024-03-29 18:33
HOW TO HAVE SONOMA 14.4/14.4.1 WORKING IN A NON-METAL iMAC
 
I installed Sonoma 14.4 on a 10.1 iMac with non-metal GPU and had the same problem. I tried several times and was able to see that without root patches installed the top menu bar appears and the keyboard worked as usually, even though the computer is very sluggish. I managed for a first time to have everything working letting the screen turn off after computer turned on and only then trying to enter my account. But then when when the screen turned off again the keyboard was not working (via bluetooth or via USB-cable) and I was not able to write the password to enter my account. So had to retry to enter with everything working and disabled the password requirement after the screen turn off. I even autoupdated to Sonoma 14.4.1 and after the first time entering to my account had to install root patches and after that the lack of the top menu bar and the keyboard was not working. Had to try to enter several times and now managed to enter my account with everything working with the following procedure:
-Turned on the computer;
-After the screen showed the prompt to enter my password I waited for the screen to turn of (5 minutes) to try to enter for the first time;
-The first time is always unsuccessful and the screen to shows the prompt to enter the password once again;
-Waited for the second time (5 minutes) for the screen to turn off and only then typed the password to enter my account;
-This second time even though it took quite while to enter my account some time after showing the background image, the top menu bar appeared and some seconds later all the apps in it started to work.

So, now I have my 10.1 non-metal iMac working normally in Sonoma 14.4.1 and the only minor issue I notice is that the mouse point disappears after some time not being used and have to move the mouse in the direction of the top menu bar and into some menu and it appears once again. This does not happen so often.

**Comment by zolero** [comment] 2024-04-02 11:04
So when is this going to be fixed?... I mean It bricked my imac's.

**Comment by Coopydood** [comment] 2024-04-02 11:10
> So when is this going to be fixed?... I mean It bricked my imac's.

I have no idea. I'm not a developer of OpenCore or have affiliation with the team. This project is merely a KVM-based implementation of it. 

I've left this thread open because it appears useful for some people but please note **this project is NOT based on the development of OpenCore itself.**

**Comment by jim-p** [comment] 2024-04-02 13:07
I was following along this thread because it had some useful info as people were investigating the problems but solutions have been posted elsewhere and not copied back here, since they were not necessarily related to this specific project.

For instances with OpenCore Legacy Patcher, their latest release resolves all the problems for non-metal devices (OCLP version 1.4.3 -- https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/1.4.3 ).

For VMs on Proxmox VE/KVM/qemu the fix is to change the USB devices to XHCI, for example using an args line like this:

```
args: -device isa-applesmc,osk="<redacted>" -smbios type=2 -device qemu-xhci -
device usb-kbd -device usb-tablet -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off -cpu host,k
vm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc
```

YMMV on the specifics depending on the host hardware.

**Comment by Coopydood** [comment] 2024-04-02 23:42
Fixed successfully by ripping out the EHCI! Pushing the updated configs in 0.11.2 tonight.

**Closed** 2024-04-18 18:53 UTC
Labels: Bug, Known Issue, Completed
